
export const ENDPOINTS = {
  VERIFYEMAIL: `/organisations/verify-email`,
  VERIFYOTP: `/organisations/verify-otp`,
  UPLOADFILE: `upload-file`,
  ORGANISATIONREGISTER: `/organisations/register`,
  ADMINLOGIN: `/organisations/signin`,
  GETPROFILE: `/organisations/profile`,
  GETALL_EMPLOYEES: `/employees`,
  CREATE_EMPLOYEE: `/employees`,
  UPDATE_EMPLOYEE: `/employees`,
  DELETE_EMPLOYEE: `/employees`,
  GET_EMPLOYEE_BY_ID: `/employees`,
  CREATE_NEW_ROLE: `/roles`,
  GET_ALL_ROLE: `/roles`,
  ASSIGN_NEW_ROLE: `/roles/assign`,
  FILTER_EMPLOYEE: `/employees/filter`,
  Employeelogin: `/employees/signin`,
  HrGetEmployeeList: `/employees`,
  EmployeeProfile: `/employees/profile`,
  GET_LEAVE_LIST: `/leaves/all-leaves`,
  UPDATE_LEAVE_APPROVAL: `/leaves`,
  ADD_HOLIDAY_LIST: `/holidays/add`,
  GET_HOLIDAY_LIST: `/holidays/all`,
  UPDATE_HOLIDAY_LIST: `/holidays/edit`,
  DELETE_HOLIDAY_LIST: `/holidays/delete`,
  GET_PAYROLL_LIST: ``,
  CREATE_CLIENT: `/sales/create-client`,
  CREATE_MEETING_NOTES: `/sales/meeting-note`,
  Get_All_Client: `/sales/fetch-my-clients`,
  Get_All_Cse_Sales: `/customer-support/fetch-cse`,
  Assign_Cse_Sales: `/customer-support/visit-schedule`,
  Get_Active_Client_Sales: `/sales/fetch-active-clients`,
  GET_MONTHLY_LEADER_BOARD: `/sales-supervisor/fetch-monthly-leaderboard`,
  GET_UPCOMING_AGENDAS: `/sales/fetch-upcoming-agendas`,
  Get_All_Client_Telecaller: `/telecaller/fetch-my-clients`,
  GET_ACTIVE_CLIENT_Telecaller: `/telecaller/fetch-active-clients`,
  TElECaLLER_MONTHLY_LEADER_BOARD: `/telecaller/fetch-monthly-leaderboard`,
  Get_All_Client_CSE: `/customer-support/visit-schedule/employee`,
  GET_ACTIVE_CLIENT_CSE: `/customer-support/fetch-active-clients`,
  CUSTOMER_SUPPORT_GENERATE_OTP: `/customer-support/generate-visit-otp`,
  CUSTOMER_SUPPORT_VERIFY_OTP: `/customer-support/verify-visit-otp`,
  Get_Lead_Client_Sales_SuperVisior: `/sales-supervisor/fetch-all-clients-leads`,
  Get_All_Sales_Executive: `/sales-supervisor/fetch-all-salesexe`,
  GET_MONTHLY_REPORT: `/report-generate/fetch-monthly-report`,
  GET_WEEKLY_REPORT: `/report-generate/fetch-weekly-report`,
  GET_TOUR_PLAN:`/tour-plan/get`
};
